import { Injectable } from '@angular/core';
import { Article } from './article';

@Injectable({
  providedIn: 'root'
})
export class ArticleService {
  Articles = [
    new Article(" UN APPARTEMENT À PARIS", 1, 35.500, '../assets/musso/musso3.jpg', false, "30/05/2017", "Paris, un atelier d’artiste caché au fond d’une allée verdoyante.Madeline l’a loué pour s’y reposer et s’isolÀ la suite d’une méprise, cette jeune flic londonienne y voit débarquer Gaspard, un écrivain misanthrope venu des États-Unis pour écrire dans la solitude. Ces deux écorchés vifs sont contraints de cohabiter quelques jours.L’atelier a appartenu au célèbre peintre Sean Lorenz et respire encore sa passion des couleurs et de la lumière. Terrassé par l’assassinat de son petit garçon, Lorenz est mort un an auparavant, laissant derrière lui trois tableaux, aujourd’hui disparus. Fascinés par son génie, intrigués par son destin funeste, Madeline et Gaspard décident d’unir leurs forces afin de retrouver ces toiles réputées extraordinaires. Mais, pour percer le véritable secret de Sean Lorenz, ils vont devoir affronter leurs propres démons dans une enquête tragique qui les changera à jamais.", "« L’art est un mensonge qui dit la vérité… »"),
    new Article("PARTI DANS LA NUIT", 2, 35.500, '../assets/musso/musso2.jpeg', true, "24/04/2018", "Un prestigieux campus secondaire enfoui dans la neige.Trois amis liés par un secret tragique.Une jeune femme disparaît dans la nuit.Côte d'Azur, hiver 1992.Vinca Rockwell, 19 ans, l'une des élèves les plus douées de sa classe post-baccalauréat, s'en va avec son professeur de philosophie avec qui elle tient un secret affaire. Pour Vinca, «l'amour c'est tout ou ce n'est rien.»Personne ne la reverra jamais.Côte d'Azur, printemps 2017.Une fois inséparables, Manon, Thomas et Maxime (les meilleurs amis de Vinca) ne se sont plus parlé depuis la fin de leurs études secondaires. Ils se voient pour la première fois en 25 ans à leur réunion de lycée. À l'époque où ils étaient étudiants, dans des circonstances terribles, les trois amis ont commis un meurtre et caché le cadavre dans un mur du gymnase de leur lycée. Maintenant, le gymnase est sur le point d'être démoli pour laisser la place à un nouveau bâtiment. Tout à coup, rien ne peut empêcher la vérité de sortir.La vérité dérangeante, douloureuse et diabolique ..", ""),
    new Article("LA VIE SECRÈTE DE L'ÉCRIVAIN", 3, 35.500, '../assets/musso/musso1.jpeg', false, "02/04/2018", "En 1999, après avoir publié trois romans cultes, le célèbre écrivain Nathan Fawles annonce la fin de sa carrière d'écrivain et se retire à Beaumont, une île magnifique et sauvage au large de la côte méditerranéenne.Automne 2018. Au cours des vingt dernières années, Fawles n'a pas donné la moindre entrevue. Alors que ses romans continuent de captiver ses lecteurs, Mathilde Monney, une jeune journaliste suisse, arrive sur l'île, résolue à révéler ses secrets. Ce même jour, le corps d'une femme est découvert sur la plage et l'île est bouclée par les autorités. C'est ainsi que commence un dangereux affrontement entre Mathilde et Nathan, dans lequel des vérités voilées se heurtent à des mensonges épars, et l'amour et la peur s'entrelacent ...Une lecture inoubliable et un fascinant casse-tête littéraire qui se révèle diabolique lorsque l'auteur met en place le dernier morceau.", "« Chacun a trois vies: une vie publique,une vie privée et une vie secrète..»"),
    new Article("LA FILLE DE BROOKLYN", 4, 28, '../assets/musso/musso4.jpg', true, "23/03/2016", "Je me souviens très bien du moment. Nous regardions la mer, l'horizon qui brillait, quand Anna posa la question:'Si je faisais quelque chose de terrible, est-ce que tu m'aimes encore?'Comment auriez-vous répondu?Anna était la femme de ma vie. Nous nous marions dans trois semaines. Bien sûr que je l'aimerais, peu importe ce qu'elle avait fait.Du moins, c'est ce que je pensais, mais elle a fébrilement fouillé dans son sac et m'a tendu une photo.- Je suis celui qui a fait ça.Je regardais son secret, abasourdie, et je savais que nos vies avaient été bouleversées pour toujours.Dans mon état de choc, je me suis levé et je suis parti sans dire un mot. À mon retour, il était trop tard: Anna avait disparu.Et je la cherche depuis.Un thriller psychologique vertigineux à la fin stupéfiante!Insupportable suspense! Une fois que vous avez ouvert le roman, vous ne le lâchez pas avant de savoir qui est vraiment cette fille de Brooklyn. Les noctambules sont à l'horizon… ”  Metronews", ""),
    new Article("C'EST TRÈS INSTANTANÉ", 5, 55.500, '../assets/musso/musso5.jpg', true, "26/03/2015", "Lisa et Arthur ne peuvent se voir qu'une fois par an.Il passe sa vie à la chercher…… elle attend la sienne.Lisa rêve de devenir actrice. Elle travaille dans un bar de Manhattan pour payer sa scolarité. Un soir, elle rencontre Arthur Costello, un jeune médecin urgentiste. Ils ont une connexion immédiate.Lisa fera tout pour le séduire. Dans une ville pleine de labyrinthes implacables, elle risque tout. Mais Arthur n'est pas comme les autres hommes. Il révèle bientôt à Lisa la terrible vérité qui l'empêche de l'aimer:«Ce qui se passe est inconcevable mais vrai…»Dans un New York plus imprévisible que jamais, Arthur et Lisa associent leurs destins pour échapper aux pièges de l'ennemi le plus impitoyable: le temps.Un thriller psychologique vertigineux à la fin stupéfiante.", ""),
    new Article("CENTRAL PARK", 6, 70.900, '../assets/musso/musso6.jpg', false, "27/03/2017", "Alice et Gabriel n'ont aucun souvenir de la nuit précédente… mais ils ne l'oublieront pas de si tôt.New York, 8h. Alice, jeune flic parisienne et Gabriel, pianiste de jazz américain, se réveillent sur un banc de Central Park menottés les uns aux autres. Ils ne se connaissent pas et n'ont aucun souvenir de s'être rencontrés. La veille au soir, Alice était à une fête avec ses copines sur les Champs-Élysées et Gabriel jouait du piano dans un club à Dublin.Impossible? Et pourtant… Tant de questions les laissent confus. Comment se sont-ils retrouvés dans une situation aussi dangereuse? Quel sang a taché la chemise d'Alice? Pourquoi manque-t-il une balle dans son arme?Alice et Gabriel n'ont d'autre choix que de faire équipe pour comprendre ce qui leur arrive et retrouver leur vie normale. Ce qu'ils vont découvrir va bouleverser leurs vies.Le suspense finement exécuté vous saisit dès les premières pages et ne lâche plus.Des personnages inoubliables, emportés par les surprises.Une lecture intense, addictive et irrésistible.", ""),
    new Article("DEMAIN", 7, 40, '../assets/musso/musso7.jpg', true, "28/02/2013", "Elle est son passé… il est son avenir. Emma habite à New York. À 32 ans, elle cherche toujours M. Droite. Matthew vit à Boston. Il a perdu sa femme dans un terrible accident et élève seul sa fille de quatre ans.Une correspondance et une correspondance fort heureuses par courrier électronique les amènent à croire qu'ils ont finalement trouvé le bonheur. Soucieux de se rencontrer, ils acceptent de se retrouver dans un petit restaurant italien à ManhatLe même jour à la même heure, ils poussent tous deux la porte du restaurant et sont présentés à la même table. Et pourtant, ils ne se croisent jamUn jeu de mensonges? Un produit de l'imagination? Une forme de manipulation? Pris dans une forme de réalité au-delà de leur compréhension, Matthew et Emma en viennent vite à comprendre qu'aucun d'eux n'était simplement debUne aventure mystérieuse et émouvaUn complot de génie en marge de la réalSuspense diabolique, intense et captivant.", ""),
    new Article("7 ANS APRÈS... ", 8, 35.500, '../assets/musso/musso8.jpg', true, "25/05/2012", "Le divorce les a séparés, le danger les ramène ensemble…Des rues de Paris au cœur de l’Amazone,un thriller impitoyable et brillamment construit.Artiste bohémienne au tempérament ardent, Nikki fait son entrée dans la vie sensée et bien ordonnée de Sebastian. Bien qu'opposés à tous égards, ils s'aiment passionnément. Peu de temps après, ils se marient et ont des jumeaux: Camille et Jeremy.Mais le mariage avance rapidement vers une fin amère: accusations, affaires, mépris… La haine prend peu à peu la place de l'amour dans leur relation. Après un divorce orageux, chaque parent a la garde d'un enfant: Sebastian fournit à sa fille une éducation très stricte, tandis que Nikki est trop indulgente face à l'inconduite de son fils.Les années passent. Ils reconstruisent tous les deux leur vie, le plus loin possible les uns des autres.Puis un jour, Jeremy disparaît mystérieusement. At-il fui? At-il été kidnappé? Nikki n'a d'autre choix que de se tourner vers son ex-mari qu'elle a à peine vu depuis sept ans pour sauver ce qui lui est le plus cher. Obligés de joindre leurs forces, Nikki et Sebastian poursuivent leur fils et retrouvent l'intimité qu'ils pensaient perdue à jamais.", ""),
    new Article("L'APPEL DE L'ANGE", 9, 60, '../assets/musso/musso9.jpg', true, "31/03/2011", "Ce qui commence comme une comédie romantique se transforme progressivement en  un thriller de haut volUne intrigue magistrale entraînée par des personnages en Une finale superbement Deux vies entières contenues dans deux minuscules téléphones New York, aéroport JFKDans un salon d'aéroport bondé, un homme et une femme se rencontrent littéralement et renversent leurs affaires par terre. Après un bref match de cri, ils se séparentMadeline et Jonathan ne se sont jamais rencontrés auparavant et n'auraient jamais dû se revoir. Cependant, alors qu'ils se dépêchaient de ramasser leurs affaires, ils changèrent de téléphone portable. Lorsqu'ils réalisent leur erreur, ils sont déjà séparés de plus de 10 000 km: elle est fleuriste à Paris et il possède un restaurant à San FranciscoIls ne tardent pas à céder à la tentation et à explorer le contenu des téléphones de chacun. Une indiscrétion de part et d'autre, mais qui conduit à une révélation inattendue: leur vie est liée par un secret selon lequel les deux pensées resteraient enfouies à jamais…", ""),
    new Article("LA FILLE DE PAPIER", 10, 100, '../assets/musso/musso10.jpg', true, "01/04/2010", "La fiction peut-elle influencer la vie réelle? «Elle est apparue sur ma terrasse par une nuit orageuse, trempée et complètement nue- D'où  viens- tu  - Je suis - Est tombé de quoi- Coupé de votre livre. Tu sais, hors de ton histoireTom Boyd, un écrivain célèbre qui souffre de blocages d'écrivains, rencontre un jour l'héroïne de ses romans. Elle est jolie, désespérée et lui dit qu'elle mourra s'il cesse d'écrireImpossible? Et Tom et Billie vont se lancer dans une aventure où la réalité et la fiction sont intimement liées, évoluant constamment dans un jeu séduisant et potentiellement mortel...", ""),
    new Article("QUE SERAIS-JE SANS TOI?", 11, 30, '../assets/musso/musso11.jpg', true, "30/04/2009", "Des toits de Paris au soleil de San FranciscoUne histoire de premier amour qui éclaire toute une vieUne conclusion magistrale et profondément émouvante.Gabrielle a deux hommes dans sa vie.L'un est son père, l'autre son premier amour.L'un est un grand flic, l'autre un voleur célèbre.Ils sont partis depuis longtemps, ayant laissé un espace vide dans son cœur.Le même jour, à la même heure, elles réapparaissent, bouleversant sa vie. Ils se connaissent, se détestent et se lancent à la poursuite de la mort.Gabrielle refuse de choisir entre eux, elle veut les garder tous les deux en sécurité, les rapprocher, les aimer tous les deux. Mais il y a des combats pour lesquels le seul résultat possible est la mort.Sauf si…", ""),
    new Article("JE REVIENS TE CHERCHER", 12, 35.500, '../assets/musso/musso12.jpg', false, "17/04/2008", "Là où il y a de l'amour, il n'y a pas Un matin, Ethan, l'un des plus brillants thérapeutes de Manhattan, reçoit une lettre de Céline, la femme qu'il a aimée et qu'il a quittée, afin de poursuivre une carrière fulgurante. C'est son Ethan est riche, célèbre, mais terriblement seul et se rend compte qu'il a perdu sa Il lui reste un jour pour réparer son erreur et récupérer Céline. 24 heures folles et mystérieuses au terme desquelles il sera tué par un Et c'est à ce moment qu'un miracle se produit: le jour recommence. Ethan se réveille, au même endroit, au même moment, comme si le destin lui donnait une seconde chance, de revivre ce moment décisif de sa Va-t-il réussir cette fois-ci à trouver le bonheur?", "")


  ];
  constructor() { }
  public getProduitByID(id: number): Article {
    for (let p of this.Articles) {
      if (p.id === id)
        return p;
    }
    return null;
  }

  public addProduit(nom: string, id: number, prix: number, photo: string, disp: boolean, datef: string, re: string, cit: string): boolean {
    if (this.getProduitByID(id) == null) {
      this.Articles.push(new Article(nom, id, prix, photo, disp, datef, re, cit));
      return true;
    }
    return false;
  }
  public supprimerLivre(id: number) {
    for (let i = 0; i < this.Articles.length; i++)
      if (this.Articles[i].id == id) {

        this.Articles.splice(i, 1);
        return true;
      }
      else { return false; }
  }
  public modiferLivre(id2: number, prix: number, nom: string) {
    for (let i = 0; i < this.Articles.length; i++) {
      if (this.Articles[i].id == id2) {
        this.Articles[i].prix = prix;
        this.Articles[i].Nom = nom;


        return true;
      }
      else { return false; }
    }
  }
}



